[features]
seeds = false
skip-lint = false
[programs.localnet]
pdas = "6YUwr858zf9n8rwdYxTCNEhek12S3inTQUDjKRk6bPdX"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/praky/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
